### ISSUE TITLE
Session store not set on request.

### ISSUE THREAD

**Issue by ILABUTK** [modemb/larasar#10]
http://localhost:8080/register

Returns: 

(RuntimeException(code: 0): Session store not set on request. at /Users/***/Downloads/larasar-master/vendor/laravel/framework/src/Illuminate/Http/Request.php:483)

**Comment by modemb** [comment]
> http://localhost:8080/register
> 
> Returns:
> 
> (RuntimeException(code: 0): Session store not set on request. at /Users/***/Downloads/larasar-master/vendor/laravel/framework/src/Illuminate/Http/Request.php:483)

It still doing it?
