### ISSUE TITLE
Error Npm run dev

### ISSUE THREAD

**Issue by carlosaroca** [modemb/larasar#22]
![image](https://user-images.githubusercontent.com/42590499/110691534-43b50d00-81b3-11eb-85e2-b526343502b3.png)
Show me this error when I run Npm run dev, I try delete node_modules and re install but no works

**Comment by modemb** [comment]
dekete the package-lock file and  try it again

**Comment by carlosaroca** [comment]
> dekete the package-lock file and try it again

I did this but this is not working yet, maybe if you can helpme through Facebook or my email I will pay u for the work. I need this carlosarocac@gmail.com

**Comment by modemb** [comment]
Ok sure, how much would you pay?

Mohamed DEMBELE - on the go
Software Engineer
MoDemb.com
Suguffie.com, World Marketplace
Skype: modemb
±1 514 922 5392 (CA) Whatsapp
+1 410 645 0520 (US)
